### PR TITLE
BLUE-1814 remove id for activity definitions' argument definition & metadata in order to solve the ordering issue on updates

### PR DESCRIPTION
**Pull request by coutinol**

### CODE REVIEW

**Review by elodietinland — APPROVED** [review]

**Review by jerome-leanspace — APPROVED** [review]
Can you just fix the `examples/resources/leanspace_activity_definitions.tf` example if you have time?

**Comment by coutinol** [comment]
> Can you just fix the `examples/resources/leanspace_activity_definitions.tf` example if you have time?

what is the issue with this file? (id is not referenced here)

**Comment by jerome-leanspace** [comment]
> > Can you just fix the `examples/resources/leanspace_activity_definitions.tf` example if you have time?
> 
> what is the issue with this file? (id is not referenced here)

identifier  = "Binary ARRAY" should be removed and the `local.arguments` don't exist in the command_mapping maybe you can put some simple names (strings) instead

**Comment by coutinol** [comment]
> > > Can you just fix the `examples/resources/leanspace_activity_definitions.tf` example if you have time?
> > 
> > 
> > what is the issue with this file? (id is not referenced here)
> 
> identifier = "Binary ARRAY" should be removed and the `local.arguments` don't exist in the command_mapping maybe you can put some simple names (strings) instead

done

**Review by jerome-leanspace — APPROVED** [review]

**Review by jerome-leanspace — APPROVED** [review]

**Pull request merged**
