### PR TITLE
SDEVOPS-365 - Added approval step to terraform release

### PR DESCRIPTION
**Pull request by priteshkanojiya**
- Changes made in this PR will ensure that before new versions of terraform repository are released to the customers, either @jerome-leanspace or @elodietinland would have to approve the release to allow it to be deployed.

### CODE REVIEW

**Comment by priteshkanojiya** [comment]
I think this repository also needs branch protection and CODEOWNERS. @jerome-leanspace let me know what you think about it?

**Comment by jerome-leanspace** [comment]
> I think this repository also needs branch protection and CODEOWNERS. @jerome-leanspace let me know what you think about it?

I had to disable the branch protection because we do commit on main when there is change to the documentation. If you have an idea to make it work, please tell me :)
For the codeowners, that would be great

**Comment by jerome-leanspace** [comment]
We should have more people that can approve but I guess we can have them when they start learning about terraform

**Review by jerome-leanspace — APPROVED** [review]

**Comment by priteshkanojiya** [comment]
> > I think this repository also needs branch protection and CODEOWNERS. @jerome-leanspace let me know what you think about it?
> 
> I had to disable the branch protection because we do commit on main when there is change to the documentation. If you have an idea to make it work, please tell me :) For the codeowners, that would be great

Sure. I'll see if I can find a way for the use case. :+1:

**Pull request merged**
